package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Ariel Simao
 */
public class MovimentarCalculadora extends javax.swing.JFrame {
    Calculadora calc;
    /**
     * Creates new form MovimentarCalculadora
     */
    public MovimentarCalculadora() {
        initComponents();
        calc = new Calculadora();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoVisor = new javax.swing.JTextField();
        javax.swing.JButton botao0 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botaoPontoDecimal = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botaoDiv = new javax.swing.JButton();
        botaoMultiplicar = new javax.swing.JButton();
        botaoMenos = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        botaoMais = new javax.swing.JButton();
        botaoZerar = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoPorcentagem = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        logHistorico = new javax.swing.JTextArea();
        textoVisor2 = new javax.swing.JTextField();
        limparLogHistorico = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.green);
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        textoVisor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textoVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoVisor.setText("0");
        textoVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoVisor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textoVisor.setRequestFocusEnabled(false);
        textoVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoVisorKeyTyped(evt);
            }
        });

        botao0.setText("0");
        botao0.setToolTipText("");
        botao0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao0MouseClicked(evt);
            }
        });

        botao1.setText("1");
        botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1MouseClicked(evt);
            }
        });

        botao4.setText("4");
        botao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao4MouseClicked(evt);
            }
        });

        botao7.setText("7");
        botao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao7MouseClicked(evt);
            }
        });

        botaoPontoDecimal.setText(".");
        botaoPontoDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPontoDecimalMouseClicked(evt);
            }
        });

        botao2.setText("2");
        botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2MouseClicked(evt);
            }
        });

        botao5.setText("5");
        botao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao5MouseClicked(evt);
            }
        });

        botao8.setText("8");
        botao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao8MouseClicked(evt);
            }
        });

        botao3.setText("3");
        botao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao3MouseClicked(evt);
            }
        });

        botao6.setText("6");
        botao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao6MouseClicked(evt);
            }
        });

        botao9.setText("9");
        botao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao9MouseClicked(evt);
            }
        });

        botaoDiv.setText("/");
        botaoDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDivMouseClicked(evt);
            }
        });

        botaoMultiplicar.setText("*");
        botaoMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMultiplicarMouseClicked(evt);
            }
        });

        botaoMenos.setText("-");
        botaoMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMenosMouseClicked(evt);
            }
        });

        botaoIgual.setText("=");
        botaoIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIgualMouseClicked(evt);
            }
        });

        botaoMais.setText("+");
        botaoMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMaisMouseClicked(evt);
            }
        });

        botaoZerar.setText("CE");
        botaoZerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoZerarMouseClicked(evt);
            }
        });

        botaoApagar.setText("<-");
        botaoApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoApagarMouseClicked(evt);
            }
        });

        botaoLimpar.setText("C");
        botaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparMouseClicked(evt);
            }
        });

        botaoPorcentagem.setText("%");
        botaoPorcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPorcentagemMouseClicked(evt);
            }
        });

        logHistorico.setColumns(5);
        logHistorico.setRows(5);
        logHistorico.setText("Sem histórico");
        logHistorico.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico"));
        logHistorico.setFocusTraversalPolicyProvider(true);
        logHistorico.setKeymap(null);
        logHistorico.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        logHistorico.setOpaque(false);
        logHistorico.setVerifyInputWhenFocusTarget(false);
        logHistorico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                logHistoricoKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(logHistorico);

        textoVisor2.setEditable(false);
        textoVisor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoVisor2.setBorder(null);
        textoVisor2.setCaretColor(new java.awt.Color(153, 153, 153));
        textoVisor2.setRequestFocusEnabled(false);
        textoVisor2.setVerifyInputWhenFocusTarget(false);

        limparLogHistorico.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        limparLogHistorico.setText("Limpar Log");
        limparLogHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparLogHistoricoMouseClicked(evt);
            }
        });

        menuArquivo.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        jMenuBar1.add(menuArquivo);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botao8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoZerar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoPontoDecimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(botao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(botao5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(botao6))
                            .addComponent(botaoPorcentagem)
                            .addComponent(botao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoIgual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoDiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMenos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(textoVisor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoVisor2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparLogHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoVisor2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoApagar)
                            .addComponent(botaoLimpar)
                            .addComponent(botaoZerar)
                            .addComponent(botaoPorcentagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao7)
                            .addComponent(botao8)
                            .addComponent(botaoDiv)
                            .addComponent(botao9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao5)
                            .addComponent(botao6)
                            .addComponent(botaoMultiplicar)
                            .addComponent(botao4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao3)
                            .addComponent(botao2)
                            .addComponent(botaoMenos)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparLogHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPontoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao0MouseClicked
        try {
            inserirNumero("0");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 0 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao0MouseClicked

    private void botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseClicked
        try {
            inserirNumero("1");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 1 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao1MouseClicked

    private void botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseClicked
        try {
            inserirNumero("2");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 2 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao2MouseClicked

    private void botao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao3MouseClicked
        try {
            inserirNumero("3");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 3 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao3MouseClicked

    private void botao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao4MouseClicked
        try {
            inserirNumero("4");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 4 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao4MouseClicked

    private void botao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao5MouseClicked
        try {
            inserirNumero("5");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 5 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao5MouseClicked

    private void botao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao6MouseClicked
        try {
            inserirNumero("6");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 6 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao6MouseClicked

    private void botao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao7MouseClicked
        try {
            inserirNumero("7");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 7 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao7MouseClicked

    private void botao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao8MouseClicked
        try {
            inserirNumero("8");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 8 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao8MouseClicked

    private void botao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao9MouseClicked
        try {
            inserirNumero("9");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao 9 - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botao9MouseClicked

    private void botaoZerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoZerarMouseClicked
        try {
            textoVisor.setText("0");
            calc.zerarCE();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao CE - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoZerarMouseClicked

    private void botaoApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoApagarMouseClicked
        try {
            if(textoVisor.getText().length()>=1){
                textoVisor.setText(textoVisor.getText(0, textoVisor.getSelectionEnd()-1));
            }
            if("".equals(textoVisor.getText())||textoVisor.getText().length()<-1){
                textoVisor.setText("0");
            }else{
               
            }
        } catch (Exception e) {
            if("0".equals(textoVisor.getText())){
               textoVisor.setText("0");
            }else{
            JOptionPane.showMessageDialog(null, "Botao Apagar - Error: " + e.getMessage() + "\nContate o administrador do sistema");
            }
        }
    }//GEN-LAST:event_botaoApagarMouseClicked

    private void botaoPontoDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPontoDecimalMouseClicked
        try {
            if(!(textoVisor.getText().contains(".")))
                textoVisor.setText(textoVisor.getText() + ".");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao Ponto Decimal - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoPontoDecimalMouseClicked

    private void botaoMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMaisMouseClicked
        try {
            double valor = Double.parseDouble(textoVisor.getText());  
            logTemporario("+");
            calc.somar(valor);
            logTemporario("=");  
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(null, "Botao Mais - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoMaisMouseClicked

    private void botaoMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMenosMouseClicked
        try {   
            double valor = Double.parseDouble(textoVisor.getText());
            logTemporario("-");
            calc.subtrair(valor);
            logTemporario("=");
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(null, "Botao Menos - Error: " + e.getMessage() + "\n Contate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoMenosMouseClicked

    private void botaoMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMultiplicarMouseClicked
         try {
            double valor = Double.parseDouble(textoVisor.getText());
            logTemporario("*");
            calc.multiplicar(valor);
            logTemporario("=");
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(null, "Botao Multiplicar - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoMultiplicarMouseClicked

    private void botaoDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDivMouseClicked
        try {
            double valor = Double.parseDouble(textoVisor.getText());
            logTemporario("/");
            calc.dividir(valor);
            logTemporario("=");
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(null, "Botao Dividir - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoDivMouseClicked

    private void botaoIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIgualMouseClicked
        try {           
            double valor = Double.parseDouble(textoVisor.getText());
            String aux = String.valueOf(calc.getResultado());
            calc.resultar(valor);
            String resultado = String.valueOf(calc.getResultado());
            if("0.0".equals(resultado))
                resultado = "0";
            if(resultado.endsWith(".0")){
                resultado = resultado.substring(0, resultado.length()-2);
            }
            if("0".equals(textoVisor2.getText()))
                    textoVisor2.setText("");
            if("Sem histórico".equals(logHistorico.getText()))
                logHistorico.setText("");
            if(textoVisor2.getText().contains("%")){
                logHistorico.setText(logHistorico.getText() + textoVisor2.getText() + " = " + resultado + "\n");
            }else if(!(" ".equals(calc.getOperador())) && "".equals(textoVisor2.getText()) && !aux.equals(textoVisor.getText())){
                if(aux.endsWith(".0")){
                    aux = aux.substring(0, aux.length()-2);
                }
                logHistorico.setText(logHistorico.getText() + aux + calc.getOperador() + calc.getValor2() + " = " + resultado + "\n");
            }
            else if(!(" ".equals(calc.getOperador())) && "".equals(textoVisor2.getText()) && calc.getEstadoOperador()==false){       
                logHistorico.setText(logHistorico.getText() + textoVisor.getText() + calc.getOperador() + calc.getValor2() + " = " + resultado + "\n");
            }else{
                logHistorico.setText(logHistorico.getText() + textoVisor2.getText() + textoVisor.getText() + " = " + resultado + "\n");
            }
            textoVisor.setText(resultado);
            textoVisor2.setText("");
            calc.setEstadoIgual(true);
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(textoVisor, e.getMessage());
        }
    }//GEN-LAST:event_botaoIgualMouseClicked

    private void botaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparMouseClicked
        try {
            textoVisor.setText("0");
            calc.zerarC();
            textoVisor2.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Botao Limpar - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        } 
    }//GEN-LAST:event_botaoLimparMouseClicked

    private void botaoPorcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPorcentagemMouseClicked
        try {
            if("*".equals(calc.getOperador())){
            double valor = Double.parseDouble(textoVisor.getText());
            logTemporario("%");
            calc.porcentagem(valor); 
            logTemporario("=");
            }else{
                textoVisor2.setText("0");
                textoVisor.setText("0");
            }
        } catch (NumberFormatException | DivisaoImpossivelException e) {
            JOptionPane.showMessageDialog(null, "Botao Porcentagem - Error: " + e.getMessage() + "\nContate o administrador do sistema");
        }
    }//GEN-LAST:event_botaoPorcentagemMouseClicked

    private void textoVisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoVisorKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        if("".equals(textoVisor.getText())){
            textoVisor.setText("0");
        }
            
    }//GEN-LAST:event_textoVisorKeyTyped
    
    private void logTemporario(String operador){
        try {
            if("0".equals(textoVisor2.getText())){
                textoVisor2.setText("");
            }
            if(calc.getEstadoOperador()==false && "=".equals(operador)){
                String resultado = String.valueOf(calc.getResultado());
                if("0.0".equals(calc.getValor2())){
                    resultado = calc.getValor1();
                }
                if("0.0".equals(resultado))
                    resultado = "0";        
                if(resultado.endsWith(".0")){
                    resultado = resultado.substring(0, resultado.length()-2);
                }
                calc.setEstadoIgual(false);
                textoVisor.setText(resultado); 
            }else if(calc.getEstadoOperador()==true){
                textoVisor2.setText(textoVisor2.getText() + textoVisor.getText() + operador);
            }else if(calc.getEstadoOperador()==false  && !"".equals(calc.getOperador())){
                textoVisor2.setText(textoVisor2.getText(0, textoVisor2.getSelectionEnd()-1) + operador);
            }      
        } catch (Exception e) {
            if("Length must be positive".equals(e.getMessage())){
                String resultado = String.valueOf(calc.getResultado());
                if("0.0".equals(resultado))
                    resultado = "0";  
                if(resultado.endsWith(".0")){
                    resultado = resultado.substring(0, resultado.length()-2);
                }
                textoVisor2.setText(resultado + operador);
            }else{
                JOptionPane.showMessageDialog(null, "Em log temporario aconteceu o erro: " + e.getMessage() + "\nContate o administrador do sistema");       
            }
        }
    }
    
    private void inserirNumero(String num){
        if((!(" ".equals(calc.getOperador())))&&(calc.getEstadoOperador()==false)){
            textoVisor.setText("");
        }    
        calc.setEstadoOperador(true);
        if("0".equals(textoVisor.getText()))
            textoVisor.setText("");
        textoVisor.setText(textoVisor.getText() + num);        
    }
    
    private void limparLogHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparLogHistoricoMouseClicked
        logHistorico.setText("Sem histórico");
    }//GEN-LAST:event_limparLogHistoricoMouseClicked

    private void logHistoricoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logHistoricoKeyTyped
        if(logHistorico.getText().length()<13){
            logHistorico.setText("Sem histórico");
        }
    }//GEN-LAST:event_logHistoricoKeyTyped

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        Sobre sb = new Sobre(this, true);
        sb.setLocationRelativeTo(null);
        sb.setVisible(true);
    }//GEN-LAST:event_menuSobreMouseClicked

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoDiv;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoMais;
    private javax.swing.JButton botaoMenos;
    private javax.swing.JButton botaoMultiplicar;
    private javax.swing.JButton botaoPontoDecimal;
    private javax.swing.JButton botaoPorcentagem;
    private javax.swing.JButton botaoZerar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton limparLogHistorico;
    private javax.swing.JTextArea logHistorico;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JTextField textoVisor;
    private javax.swing.JTextField textoVisor2;
    // End of variables declaration//GEN-END:variables
}
